mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
proxies:
- name: 202.61.205.86:4433-86ab16f5
  type: hysteria2
  server: 202.61.205.86
  port: 4433
  password: 18cf8030-1ceb-4b7d-8c0c-c036413c144e
  sni: de1.xiaoliyu.cyou
  skip-cert-verify: true
- name: quran.mci.ai:443-6fd61732
  type: hysteria2
  server: quran.mci.ai
  port: 443
  password: 28c05d48e2f470d07a4c392c9bd43849
  sni: quran.mci.ai
- name: 140.233.177.48:33884-b46141f7
  type: hysteria2
  server: 140.233.177.48
  port: 33884
  password: 3uIVdQh2vc
  sni: www.oracle.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: t-me-V2RayyNGvpn
- name: jongjmi.odnako.site:8449-49fe8c21
  type: hysteria2
  server: jongjmi.odnako.site
  port: 8449
  password: 792V1zl5cJHSV3wjyGPXiFbx1YA4BrIr
  sni: jongjmi.odnako.site
- name: 45.155.103.217:8443-cea56744
  type: hysteria2
  server: 45.155.103.217
  port: 8443
  password: 87qety_hERGP8Y9_jqier3gw_nA8Q34_B2
  sni: kamil-power-machine.roxa.org
- name: qg.easyiran.org:56845-57658214
  type: hysteria2
  server: qg.easyiran.org
  port: 56845
  password: 91uokb9ud7raz0fk
  sni: qg.easyiran.org
  obfs: salamander
  obfs-password: ngljeqgna3hmfr2s
- name: de1.jamezwin.org:443-9f106fa2
  type: hysteria2
  server: de1.jamezwin.org
  port: 443
  password: 9204bccb42c743799c6069feccb7832d
  sni: de1.jamezwin.org
  obfs: salamander
  obfs-password: u3do5j2gss7mfri9
- name: 91.107.152.188:40460-fbeb45cd
  type: hysteria2
  server: 91.107.152.188
  port: 40460
  password: 92QgVKZjWa
  sni: www.amd.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: t-me-V2RayyNGvpn
- name: 46.8.210.209:443-04360e96
  type: hysteria2
  server: 46.8.210.209
  port: 443
  password: 95c61940-2823-4665-a033-d4f2218329b6
  sni: ru3.kinotorg.net
- name: srm.kishonline.online:443-11d02e0d
  type: hysteria2
  server: srm.kishonline.online
  port: 443
  password: 9P5zfc7S0s
  sni: srm.kishonline.online
  obfs: salamander
  obfs-password: kish-data-center
- name: 18.157.222.169:54040-a7ff10a3
  type: hysteria2
  server: 18.157.222.169
  port: 54040
  password: '@Masir_Sefid'
  sni: free.masir-sefid.shop
  obfs: salamander
  obfs-password: Masir_Sefid
- name: 91.107.152.188:31999-5c1eb00e
  type: hysteria2
  server: 91.107.152.188
  port: 31999
  password: ALg6h4f8Mo
  sni: www.amd.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: t-me-V2RayyNGvpn
- name: 103.115.109.49:443-74006b38
  type: hysteria2
  server: 103.115.109.49
  port: 443
  password: H7mP2xY9kJ4nQ8wR5tF6vB3z
  sni: https://t.me/oneclickvpnkeys
  skip-cert-verify: true
- name: 18.141.232.182:443-4fe66031
  type: hysteria2
  server: 18.141.232.182
  port: 443
  password: H7mP2xY9kJ4nQ8wR5tF6vB3z
  sni: https://t.me/WangCai2🇨🇳
  skip-cert-verify: true
- name: 18.190.219.163:443-3d64735b
  type: hysteria2
  server: 18.190.219.163
  port: 443
  password: H7mP2xY9kJ4nQ8wR5tF6vB3z
  sni: https://t.me/WangCai2🇨🇳
  skip-cert-verify: true
- name: 34.212.146.99:443-eac30bc5
  type: hysteria2
  server: 34.212.146.99
  port: 443
  password: H7mP2xY9kJ4nQ8wR5tF6vB3z
  sni: https://t.me/WangCai2🇨🇳
  skip-cert-verify: true
- name: 34.219.182.57:443-6f6bb91a
  type: hysteria2
  server: 34.219.182.57
  port: 443
  password: H7mP2xY9kJ4nQ8wR5tF6vB3z
  skip-cert-verify: true
- name: 44.245.99.184:443-1a607e8c
  type: hysteria2
  server: 44.245.99.184
  port: 443
  password: H7mP2xY9kJ4nQ8wR5tF6vB3z
  sni: https://t.me/WangCai2🇨🇳
  skip-cert-verify: true
- name: 54.245.180.117:443-936476cf
  type: hysteria2
  server: 54.245.180.117
  port: 443
  password: H7mP2xY9kJ4nQ8wR5tF6vB3z
  skip-cert-verify: true
- name: 91.107.152.188:40460-94db3854
  type: hysteria2
  server: 91.107.152.188
  port: 40460
  password: JxCHTtg2gX
  sni: www.amd.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: t-me-V2RayyNGvpn
- name: 91.107.174.32:25810-e00c35af
  type: hysteria2
  server: 91.107.174.32
  port: 25810
  password: KJX4HQHodA
  sni: www.amd.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: T-ME-V2RayyNGvpn
- name: 179.61.132.96:8443-4061812f
  type: hysteria2
  server: 179.61.132.96
  port: 8443
  password: KevinZakarian
  sni: 179.61.132.96
  skip-cert-verify: true
  obfs: salamander
  obfs-password: KevinZakarian
- name: 91.107.152.188:31999-4f6df364
  type: hysteria2
  server: 91.107.152.188
  port: 31999
  password: M4q4riAk3C
  sni: www.amd.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: t-me-V2RayyNGvpn
- name: 91.107.152.188:40460-b85521ae
  type: hysteria2
  server: 91.107.152.188
  port: 40460
  password: NZC2w2V2NQ
  sni: www.amd.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: t-me-V2RayyNGvpn
- name: 91.107.152.188:31999-e9e25df7
  type: hysteria2
  server: 91.107.152.188
  port: 31999
  password: Ov5kSglMCd
  sni: www.amd.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: t-me-V2RayyNGvpn
- name: 185.126.236.152:8443-9d7fd893
  type: hysteria2
  server: 185.126.236.152
  port: 8443
  password: Ov_98eqvJ9N8SE3_Bxhr238e_Ntz2_Sxc47_J2
  sni: key-hm-at.1cooldns.com
- name: 91.107.152.188:31999-a49efc8f
  type: hysteria2
  server: 91.107.152.188
  port: 31999
  password: RKJDOKrcIZ
  sni: www.amd.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: t-me-V2RayyNGvpn
- name: pristytools.com.pristytools.com:2053-ba7dd424
  type: hysteria2
  server: pristytools.com.pristytools.com
  port: 2053
  password: TELEGRAM-ID-soalvajavaab
  obfs: salamander
  obfs-password: dwv3ped4yi46iw8r
- name: 91.107.174.32:25810-3588c41d
  type: hysteria2
  server: 91.107.174.32
  port: 25810
  password: UUoAsk2eM4
  sni: www.amd.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: T-ME-V2RayyNGvpn
- name: 91.107.152.188:31999-e5db14dd
  type: hysteria2
  server: 91.107.152.188
  port: 31999
  password: V2RayyNGvpn-
  sni: www.amd.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: t-me-V2RayyNGvpn
- name: 51.89.225.225:58410-52dca743
  type: hysteria2
  server: 51.89.225.225
  port: 58410
  password: V2RayyNGvpn
  sni: www.oracle.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: TeLeGRam=V2RayyNGvpn
- name: 66.92.161.59:42286-a6abab22
  type: hysteria2
  server: 66.92.161.59
  port: 42286
  password: V2RayyNGvpn
  sni: www.amd.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: t-me-V2RayyNGvpn
- name: 91.107.174.32:25810-c0ce653c
  type: hysteria2
  server: 91.107.174.32
  port: 25810
  password: V2RayyNGvpn
  sni: www.amd.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: T-ME-V2RayyNGvpn
- name: 206.71.158.37:35000-11e0595d
  type: hysteria2
  server: 206.71.158.37
  port: 35000
  password: Yet-Another-Public-Config-1
  sni: YAPC-1.afshin.ir
  obfs: salamander
  obfs-password: Yet-Another-Public-Config-1
- name: 206.71.158.37:35000-627d093d
  type: hysteria2
  server: 206.71.158.37
  port: 35000
  password: Yet-Another-Public-Config-1
  sni: YAPC-1.afshin.ir¬e=@FreeOnlineVPN
  skip-cert-verify: true
  obfs: salamander
  obfs-password: Yet-Another-Public-Config-1
- name: ffc60249-t53wg0-t92wi1-1qkeg.hk2.hyhuawei.com:443-449a5abf
  type: hysteria2
  server: ffc60249-t53wg0-t92wi1-1qkeg.hk2.hyhuawei.com
  port: 443
  password: a305ac08-d136-11ee-b6db-f23c91cfbbc9
  sni: ffc60249-t53wg0-t92wi1-1qkeg.hk2.hyhuawei.com
- name: 91.107.174.32:25810-43f57bf9
  type: hysteria2
  server: 91.107.174.32
  port: 25810
  password: a6alb4YAgC
  sni: www.amd.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: T-ME-V2RayyNGvpn
- name: 181.214.99.162:35000-35d3f43c
  type: hysteria2
  server: 181.214.99.162
  port: 35000
  password: b4bd0613-ff7c-4f2f-954d-185915e6ddad
  sni: api.kermanshahi.org
  skip-cert-verify: true
  obfs: salamander
  obfs-password: '@JavidnamanIran-Javid-SHAH-KingRezaPahlavi'
- name: 5.175.249.174:35000-c6986359
  type: hysteria2
  server: 5.175.249.174
  port: 35000
  password: b4bd0613-ff7c-4f2f-954d-185915e6ddad
  sni: api.kermanshahi.org
  obfs: salamander
  obfs-password: '@JavidnamanIran-Javid-SHAH-KingRezaPahlavi'
- name: 155.248.209.237:33333-4d63cab8
  type: hysteria2
  server: 155.248.209.237
  port: 33333
  password: bce6c821-200d-421f-bf3d-7159e5246ea0
  sni: hy2.123266.xyz
- name: fast88.screw.page:443-1d8c7f7c
  type: hysteria2
  server: fast88.screw.page
  port: 443
  password: c0aa0cee-e855-4bcc-9afc-46241cb17990
  sni: fast88.screw.page
- name: 62.210.124.146:22000-9e50f969
  type: hysteria2
  server: 62.210.124.146
  port: 22000
  password: dongtaiwang.com
  sni: www.microsoft.com
  skip-cert-verify: true
- name: assets.gateway-stream.com:52000-42b50977
  type: hysteria2
  server: assets.gateway-stream.com
  port: 52000
  password: elknam6l7izf3z71
  sni: assets.gateway-stream.com
  obfs: salamander
  obfs-password: gu74jg3ym0e21zco
- name: assets.gateway-stream.com:52002-57fe804f
  type: hysteria2
  server: assets.gateway-stream.com
  port: 52002
  password: elknam6l7izf3z71
  sni: assets.gateway-stream.com
  obfs: salamander
  obfs-password: ielzukpwth087afx
- name: assets.gateway-stream.com:52013-53bd0e10
  type: hysteria2
  server: assets.gateway-stream.com
  port: 52013
  password: elknam6l7izf3z71
  sni: assets.gateway-stream.com
  obfs: salamander
  obfs-password: cukfjxud1ebjuuzs
- name: assets.gateway-stream.com:52021-8f92aaa1
  type: hysteria2
  server: assets.gateway-stream.com
  port: 52021
  password: elknam6l7izf3z71
  sni: assets.gateway-stream.com
  obfs: salamander
  obfs-password: mtg2vchyir6la3et
- name: 91.107.174.32:25810-fd63838c
  type: hysteria2
  server: 91.107.174.32
  port: 25810
  password: kfCR7ekba6
  sni: www.amd.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: T-ME-V2RayyNGvpn
- name: 130.49.161.70:443-29f3d11e
  type: hysteria2
  server: 130.49.161.70
  port: 443
  password: p7Q76LzlnS4hIzr1W3staBOnUe_WwSkR
  sni: hy2.aspidnet.xyz
  obfs: salamander
  obfs-password: rG07s3COMIEvdnQipRyWzx_H_2xygNC3
- name: 13.229.106.122:443-f2cf37d5
  type: hysteria2
  server: 13.229.106.122
  port: 443
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  sni: vpn-sg-001.fastervpn.world
  skip-cert-verify: true
- name: 13.229.110.73:443-3d7d37d4
  type: hysteria2
  server: 13.229.110.73
  port: 443
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  sni: vpn-sg-001.fastervpn.world
  skip-cert-verify: true
- name: 13.250.29.24:443-2cf3d689
  type: hysteria2
  server: 13.250.29.24
  port: 443
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  sni: vpn-sg-001.fastervpn.world
  skip-cert-verify: true
- name: 47.129.9.33:443-efb5437b
  type: hysteria2
  server: 47.129.9.33
  port: 443
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  sni: vpn-sg-001.fastervpn.world
  skip-cert-verify: true
- name: 54.251.212.188:443-6ce7825e
  type: hysteria2
  server: 54.251.212.188
  port: 443
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  sni: vpn-sg-001.fastervpn.world
  skip-cert-verify: true
- name: 54.255.220.11:443-3d942f53
  type: hysteria2
  server: 54.255.220.11
  port: 443
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  sni: vpn-sg-001.fastervpn.world
  skip-cert-verify: true
- name: 80.66.81.78:9443-c13ab0cc
  type: hysteria2
  server: 80.66.81.78
  port: 9443
  password: rs2mR3g9bZiMloftx6lZQ59Um1Ld
  sni: tunel1.washing.help
  obfs: salamander
  obfs-password: oMgvuBy5Lj5kYM57sGsnjpjNcSEQ
- name: 91.107.152.188:40460-6799e24e
  type: hysteria2
  server: 91.107.152.188
  port: 40460
  password: tf5LINcpQy
  sni: www.amd.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: t-me-V2RayyNGvpn
- name: 140.233.177.48:33884-1f82781c
  type: hysteria2
  server: 140.233.177.48
  port: 33884
  password: vVaz4PV7B7
  sni: www.oracle.com
  skip-cert-verify: true
  obfs: salamander
  obfs-password: t-me-V2RayyNGvpn
- name: 130.61.50.75:6443-495f0385
  type: hysteria2
  server: 130.61.50.75
  port: 6443
  password: zhangyang
  sni: dash.cloudflare.com
  skip-cert-verify: true
proxy-groups:
- name: AUTO
  type: url-test
  proxies:
  - 202.61.205.86:4433-86ab16f5
  - quran.mci.ai:443-6fd61732
  - 140.233.177.48:33884-b46141f7
  - jongjmi.odnako.site:8449-49fe8c21
  - 45.155.103.217:8443-cea56744
  - qg.easyiran.org:56845-57658214
  - de1.jamezwin.org:443-9f106fa2
  - 91.107.152.188:40460-fbeb45cd
  - 46.8.210.209:443-04360e96
  - srm.kishonline.online:443-11d02e0d
  - 18.157.222.169:54040-a7ff10a3
  - 91.107.152.188:31999-5c1eb00e
  - 103.115.109.49:443-74006b38
  - 18.141.232.182:443-4fe66031
  - 18.190.219.163:443-3d64735b
  - 34.212.146.99:443-eac30bc5
  - 34.219.182.57:443-6f6bb91a
  - 44.245.99.184:443-1a607e8c
  - 54.245.180.117:443-936476cf
  - 91.107.152.188:40460-94db3854
  - 91.107.174.32:25810-e00c35af
  - 179.61.132.96:8443-4061812f
  - 91.107.152.188:31999-4f6df364
  - 91.107.152.188:40460-b85521ae
  - 91.107.152.188:31999-e9e25df7
  - 185.126.236.152:8443-9d7fd893
  - 91.107.152.188:31999-a49efc8f
  - pristytools.com.pristytools.com:2053-ba7dd424
  - 91.107.174.32:25810-3588c41d
  - 91.107.152.188:31999-e5db14dd
  - 51.89.225.225:58410-52dca743
  - 66.92.161.59:42286-a6abab22
  - 91.107.174.32:25810-c0ce653c
  - 206.71.158.37:35000-11e0595d
  - 206.71.158.37:35000-627d093d
  - ffc60249-t53wg0-t92wi1-1qkeg.hk2.hyhuawei.com:443-449a5abf
  - 91.107.174.32:25810-43f57bf9
  - 181.214.99.162:35000-35d3f43c
  - 5.175.249.174:35000-c6986359
  - 155.248.209.237:33333-4d63cab8
  - fast88.screw.page:443-1d8c7f7c
  - 62.210.124.146:22000-9e50f969
  - assets.gateway-stream.com:52000-42b50977
  - assets.gateway-stream.com:52002-57fe804f
  - assets.gateway-stream.com:52013-53bd0e10
  - assets.gateway-stream.com:52021-8f92aaa1
  - 91.107.174.32:25810-fd63838c
  - 130.49.161.70:443-29f3d11e
  - 13.229.106.122:443-f2cf37d5
  - 13.229.110.73:443-3d7d37d4
  - 13.250.29.24:443-2cf3d689
  - 47.129.9.33:443-efb5437b
  - 54.251.212.188:443-6ce7825e
  - 54.255.220.11:443-3d942f53
  - 80.66.81.78:9443-c13ab0cc
  - 91.107.152.188:40460-6799e24e
  - 140.233.177.48:33884-1f82781c
  - 130.61.50.75:6443-495f0385
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
rules:
- MATCH,PROXY
