name: Update Hysteria2 Clash Config

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check files
        run: |
          ls -la
          echo "-----"
          ls -la .github/workflows

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install
        run: pip install -r requirements.txt

      - name: Generate
        run: |
          python converter.py
          echo "Generated file:"
          ls -lh config.yaml
          head -30 config.yaml

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add config.yaml

          git status

          git commit -m "Update config" || echo "Nothing changed"

          git push
